python boosting_prediction.py feature_vector/feature_vector_pca_f_std_t_one_of_k_t_label_f.pkl parameter/XGBLINEAR1.json
python boosting_prediction.py feature_vector/feature_vector_pca_f_std_t_one_of_k_t_label_f.pkl parameter/XGBLINEAR2.json
python boosting_prediction.py feature_vector/feature_vector_pca_f_std_t_one_of_k_f_label_t.pkl parameter/XGBLINEAR1.json
python boosting_prediction.py feature_vector/feature_vector_pca_f_std_t_one_of_k_f_label_t.pkl parameter/XGBLINEAR2.json
python boosting_prediction.py feature_vector/feature_vector_pca_f_std_t_one_of_k_t_label_f.pkl parameter/XGBLINEAR1.json
python boosting_prediction.py feature_vector/feature_vector_pca_f_std_t_one_of_k_t_label_f.pkl parameter/DECISIONTREE.json
python boosting_prediction.py feature_vector/feature_vector_pca_f_std_t_one_of_k_t_label_f.pkl parameter/EXREG.json
